/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "design.sv:2.1-85.10" *)
module apb_slave(PCLK, PRESETn, PSEL, PENABLE, PADDR, PWRITE, PWDATA, PREADY, PRDATA);
  (* src = "design.sv:3.9-3.13" *)
  input PCLK;
  wire PCLK;
  (* src = "design.sv:4.9-4.16" *)
  input PRESETn;
  wire PRESETn;
  (* src = "design.sv:5.9-5.13" *)
  input PSEL;
  wire PSEL;
  (* src = "design.sv:6.9-6.16" *)
  input PENABLE;
  wire PENABLE;
  (* src = "design.sv:7.15-7.20" *)
  input [1:0] PADDR;
  wire [1:0] PADDR;
  (* src = "design.sv:8.9-8.15" *)
  input PWRITE;
  wire PWRITE;
  (* src = "design.sv:9.15-9.21" *)
  input [7:0] PWDATA;
  wire [7:0] PWDATA;
  (* src = "design.sv:10.14-10.20" *)
  output PREADY;
  wire PREADY;
  (* src = "design.sv:11.20-11.26" *)
  output [7:0] PRDATA;
  wire [7:0] PRDATA;
  (* src = "design.sv:17.3-59.6" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  (* src = "design.sv:7.15-7.20" *)
  wire _067_;
  (* src = "design.sv:7.15-7.20" *)
  wire _068_;
  (* src = "design.sv:6.9-6.16" *)
  wire _069_;
  (* src = "design.sv:11.20-11.26" *)
  wire _070_;
  (* src = "design.sv:11.20-11.26" *)
  wire _071_;
  (* src = "design.sv:11.20-11.26" *)
  wire _072_;
  (* src = "design.sv:11.20-11.26" *)
  wire _073_;
  (* src = "design.sv:11.20-11.26" *)
  wire _074_;
  (* src = "design.sv:11.20-11.26" *)
  wire _075_;
  (* src = "design.sv:11.20-11.26" *)
  wire _076_;
  (* src = "design.sv:11.20-11.26" *)
  wire _077_;
  (* src = "design.sv:10.14-10.20" *)
  wire _078_;
  (* src = "design.sv:4.9-4.16" *)
  wire _079_;
  (* src = "design.sv:5.9-5.13" *)
  wire _080_;
  (* src = "design.sv:9.15-9.21" *)
  wire _081_;
  (* src = "design.sv:9.15-9.21" *)
  wire _082_;
  (* src = "design.sv:9.15-9.21" *)
  wire _083_;
  (* src = "design.sv:9.15-9.21" *)
  wire _084_;
  (* src = "design.sv:9.15-9.21" *)
  wire _085_;
  (* src = "design.sv:9.15-9.21" *)
  wire _086_;
  (* src = "design.sv:9.15-9.21" *)
  wire _087_;
  (* src = "design.sv:9.15-9.21" *)
  wire _088_;
  (* src = "design.sv:8.9-8.15" *)
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  (* src = "design.sv:15.13-15.16" *)
  wire _133_;
  (* src = "design.sv:15.13-15.16" *)
  wire _134_;
  (* src = "design.sv:15.13-15.16" *)
  wire _135_;
  (* src = "design.sv:15.13-15.16" *)
  wire _136_;
  (* src = "design.sv:15.13-15.16" *)
  wire _137_;
  (* src = "design.sv:15.13-15.16" *)
  wire _138_;
  (* src = "design.sv:15.13-15.16" *)
  wire _139_;
  (* src = "design.sv:15.13-15.16" *)
  wire _140_;
  (* src = "design.sv:15.13-15.16" *)
  wire _141_;
  (* src = "design.sv:15.13-15.16" *)
  wire _142_;
  (* src = "design.sv:15.13-15.16" *)
  wire _143_;
  (* src = "design.sv:15.13-15.16" *)
  wire _144_;
  (* src = "design.sv:15.13-15.16" *)
  wire _145_;
  (* src = "design.sv:15.13-15.16" *)
  wire _146_;
  (* src = "design.sv:15.13-15.16" *)
  wire _147_;
  (* src = "design.sv:15.13-15.16" *)
  wire _148_;
  (* src = "design.sv:15.13-15.16" *)
  wire _149_;
  (* src = "design.sv:15.13-15.16" *)
  wire _150_;
  (* src = "design.sv:15.13-15.16" *)
  wire _151_;
  (* src = "design.sv:15.13-15.16" *)
  wire _152_;
  (* src = "design.sv:15.13-15.16" *)
  wire _153_;
  (* src = "design.sv:15.13-15.16" *)
  wire _154_;
  (* src = "design.sv:15.13-15.16" *)
  wire _155_;
  (* src = "design.sv:15.13-15.16" *)
  wire _156_;
  (* src = "design.sv:15.13-15.16" *)
  wire _157_;
  (* src = "design.sv:15.13-15.16" *)
  wire _158_;
  (* src = "design.sv:15.13-15.16" *)
  wire _159_;
  (* src = "design.sv:15.13-15.16" *)
  wire _160_;
  (* src = "design.sv:15.13-15.16" *)
  wire _161_;
  (* src = "design.sv:15.13-15.16" *)
  wire _162_;
  (* src = "design.sv:15.13-15.16" *)
  wire _163_;
  (* src = "design.sv:15.13-15.16" *)
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  (* src = "design.sv:15.13-15.16" *)
  wire [7:0] \mem[0] ;
  (* src = "design.sv:15.13-15.16" *)
  wire [7:0] \mem[1] ;
  (* src = "design.sv:15.13-15.16" *)
  wire [7:0] \mem[2] ;
  (* src = "design.sv:15.13-15.16" *)
  wire [7:0] \mem[3] ;
  (* onehot = 32'd1 *)
  wire [2:0] state;
  INV_X1 _301_ (
    .A(_067_),
    .ZN(_165_)
  );
  INV_X1 _302_ (
    .A(_068_),
    .ZN(_166_)
  );
  INV_X1 _303_ (
    .A(_215_),
    .ZN(_167_)
  );
  INV_X1 _304_ (
    .A(_214_),
    .ZN(_168_)
  );
  INV_X1 _305_ (
    .A(_080_),
    .ZN(_169_)
  );
  INV_X1 _306_ (
    .A(_078_),
    .ZN(_170_)
  );
  OAI21_X1 _307_ (
    .A(_169_),
    .B1(_214_),
    .B2(_215_),
    .ZN(_171_)
  );
  OAI21_X1 _308_ (
    .A(_171_),
    .B1(_167_),
    .B2(_069_),
    .ZN(_090_)
  );
  NAND2_X1 _309_ (
    .A1(_069_),
    .A2(_215_),
    .ZN(_172_)
  );
  AOI21_X1 _310_ (
    .A(_169_),
    .B1(_172_),
    .B2(_168_),
    .ZN(_091_)
  );
  NOR2_X1 _311_ (
    .A1(_089_),
    .A2(_172_),
    .ZN(_173_)
  );
  OR2_X1 _312_ (
    .A1(_089_),
    .A2(_172_),
    .ZN(_174_)
  );
  AND2_X1 _313_ (
    .A1(_067_),
    .A2(_068_),
    .ZN(_175_)
  );
  NOR2_X1 _314_ (
    .A1(_165_),
    .A2(_068_),
    .ZN(_176_)
  );
  NOR2_X1 _315_ (
    .A1(_067_),
    .A2(_068_),
    .ZN(_177_)
  );
  NOR2_X1 _316_ (
    .A1(_067_),
    .A2(_166_),
    .ZN(_178_)
  );
  AOI22_X1 _317_ (
    .A1(_136_),
    .A2(_177_),
    .B1(_178_),
    .B2(_152_),
    .ZN(_179_)
  );
  AOI221_X1 _318_ (
    .A(_174_),
    .B1(_175_),
    .B2(_160_),
    .C1(_176_),
    .C2(_144_),
    .ZN(_180_)
  );
  NOR2_X1 _319_ (
    .A1(_073_),
    .A2(_173_),
    .ZN(_181_)
  );
  AOI21_X1 _320_ (
    .A(_181_),
    .B1(_180_),
    .B2(_179_),
    .ZN(_092_)
  );
  NAND3_X1 _321_ (
    .A1(_165_),
    .A2(_068_),
    .A3(_151_),
    .ZN(_182_)
  );
  NAND2_X1 _322_ (
    .A1(_143_),
    .A2(_176_),
    .ZN(_183_)
  );
  NOR2_X1 _323_ (
    .A1(_072_),
    .A2(_173_),
    .ZN(_184_)
  );
  AOI22_X1 _324_ (
    .A1(_159_),
    .A2(_175_),
    .B1(_177_),
    .B2(_135_),
    .ZN(_185_)
  );
  AND3_X1 _325_ (
    .A1(_173_),
    .A2(_182_),
    .A3(_185_),
    .ZN(_186_)
  );
  AOI21_X1 _326_ (
    .A(_184_),
    .B1(_186_),
    .B2(_183_),
    .ZN(_093_)
  );
  AOI22_X1 _327_ (
    .A1(_158_),
    .A2(_175_),
    .B1(_177_),
    .B2(_134_),
    .ZN(_187_)
  );
  AOI221_X1 _328_ (
    .A(_174_),
    .B1(_176_),
    .B2(_142_),
    .C1(_178_),
    .C2(_150_),
    .ZN(_188_)
  );
  NOR2_X1 _329_ (
    .A1(_071_),
    .A2(_173_),
    .ZN(_189_)
  );
  AOI21_X1 _330_ (
    .A(_189_),
    .B1(_188_),
    .B2(_187_),
    .ZN(_094_)
  );
  AOI22_X1 _331_ (
    .A1(_157_),
    .A2(_175_),
    .B1(_177_),
    .B2(_133_),
    .ZN(_190_)
  );
  AOI221_X1 _332_ (
    .A(_174_),
    .B1(_176_),
    .B2(_141_),
    .C1(_178_),
    .C2(_149_),
    .ZN(_191_)
  );
  NOR2_X1 _333_ (
    .A1(_070_),
    .A2(_173_),
    .ZN(_192_)
  );
  AOI21_X1 _334_ (
    .A(_192_),
    .B1(_191_),
    .B2(_190_),
    .ZN(_095_)
  );
  NAND4_X1 _335_ (
    .A1(_069_),
    .A2(_215_),
    .A3(_089_),
    .A4(_079_),
    .ZN(_193_)
  );
  NOR3_X1 _336_ (
    .A1(_165_),
    .A2(_068_),
    .A3(_193_),
    .ZN(_194_)
  );
  MUX2_X1 _337_ (
    .A(_147_),
    .B(_087_),
    .S(_194_),
    .Z(_096_)
  );
  MUX2_X1 _338_ (
    .A(_146_),
    .B(_086_),
    .S(_194_),
    .Z(_097_)
  );
  MUX2_X1 _339_ (
    .A(_145_),
    .B(_085_),
    .S(_194_),
    .Z(_098_)
  );
  MUX2_X1 _340_ (
    .A(_144_),
    .B(_084_),
    .S(_194_),
    .Z(_099_)
  );
  MUX2_X1 _341_ (
    .A(_143_),
    .B(_083_),
    .S(_194_),
    .Z(_100_)
  );
  MUX2_X1 _342_ (
    .A(_142_),
    .B(_082_),
    .S(_194_),
    .Z(_101_)
  );
  MUX2_X1 _343_ (
    .A(_141_),
    .B(_081_),
    .S(_194_),
    .Z(_102_)
  );
  NOR3_X1 _344_ (
    .A1(_067_),
    .A2(_068_),
    .A3(_193_),
    .ZN(_195_)
  );
  MUX2_X1 _345_ (
    .A(_139_),
    .B(_087_),
    .S(_195_),
    .Z(_103_)
  );
  NOR3_X1 _346_ (
    .A1(_165_),
    .A2(_166_),
    .A3(_193_),
    .ZN(_196_)
  );
  MUX2_X1 _347_ (
    .A(_163_),
    .B(_087_),
    .S(_196_),
    .Z(_104_)
  );
  MUX2_X1 _348_ (
    .A(_162_),
    .B(_086_),
    .S(_196_),
    .Z(_105_)
  );
  MUX2_X1 _349_ (
    .A(_161_),
    .B(_085_),
    .S(_196_),
    .Z(_106_)
  );
  MUX2_X1 _350_ (
    .A(_160_),
    .B(_084_),
    .S(_196_),
    .Z(_107_)
  );
  MUX2_X1 _351_ (
    .A(_159_),
    .B(_083_),
    .S(_196_),
    .Z(_108_)
  );
  MUX2_X1 _352_ (
    .A(_158_),
    .B(_082_),
    .S(_196_),
    .Z(_109_)
  );
  MUX2_X1 _353_ (
    .A(_157_),
    .B(_081_),
    .S(_196_),
    .Z(_110_)
  );
  OAI21_X1 _354_ (
    .A(_172_),
    .B1(_170_),
    .B2(_215_),
    .ZN(_111_)
  );
  MUX2_X1 _355_ (
    .A(_148_),
    .B(_088_),
    .S(_194_),
    .Z(_112_)
  );
  MUX2_X1 _356_ (
    .A(_138_),
    .B(_086_),
    .S(_195_),
    .Z(_113_)
  );
  AOI22_X1 _357_ (
    .A1(_164_),
    .A2(_175_),
    .B1(_177_),
    .B2(_140_),
    .ZN(_197_)
  );
  NAND3_X1 _358_ (
    .A1(_067_),
    .A2(_166_),
    .A3(_148_),
    .ZN(_198_)
  );
  NAND3_X1 _359_ (
    .A1(_165_),
    .A2(_068_),
    .A3(_156_),
    .ZN(_199_)
  );
  NAND3_X1 _360_ (
    .A1(_197_),
    .A2(_198_),
    .A3(_199_),
    .ZN(_200_)
  );
  MUX2_X1 _361_ (
    .A(_077_),
    .B(_200_),
    .S(_173_),
    .Z(_114_)
  );
  NOR3_X1 _362_ (
    .A1(_067_),
    .A2(_166_),
    .A3(_193_),
    .ZN(_201_)
  );
  MUX2_X1 _363_ (
    .A(_156_),
    .B(_088_),
    .S(_201_),
    .Z(_115_)
  );
  MUX2_X1 _364_ (
    .A(_137_),
    .B(_085_),
    .S(_195_),
    .Z(_116_)
  );
  MUX2_X1 _365_ (
    .A(_136_),
    .B(_084_),
    .S(_195_),
    .Z(_117_)
  );
  MUX2_X1 _366_ (
    .A(_164_),
    .B(_088_),
    .S(_196_),
    .Z(_118_)
  );
  MUX2_X1 _367_ (
    .A(_155_),
    .B(_087_),
    .S(_201_),
    .Z(_119_)
  );
  MUX2_X1 _368_ (
    .A(_154_),
    .B(_086_),
    .S(_201_),
    .Z(_120_)
  );
  MUX2_X1 _369_ (
    .A(_140_),
    .B(_088_),
    .S(_195_),
    .Z(_121_)
  );
  MUX2_X1 _370_ (
    .A(_153_),
    .B(_085_),
    .S(_201_),
    .Z(_122_)
  );
  MUX2_X1 _371_ (
    .A(_152_),
    .B(_084_),
    .S(_201_),
    .Z(_123_)
  );
  MUX2_X1 _372_ (
    .A(_151_),
    .B(_083_),
    .S(_201_),
    .Z(_124_)
  );
  MUX2_X1 _373_ (
    .A(_150_),
    .B(_082_),
    .S(_201_),
    .Z(_125_)
  );
  MUX2_X1 _374_ (
    .A(_149_),
    .B(_081_),
    .S(_201_),
    .Z(_126_)
  );
  MUX2_X1 _375_ (
    .A(_135_),
    .B(_083_),
    .S(_195_),
    .Z(_127_)
  );
  MUX2_X1 _376_ (
    .A(_134_),
    .B(_082_),
    .S(_195_),
    .Z(_128_)
  );
  MUX2_X1 _377_ (
    .A(_133_),
    .B(_081_),
    .S(_195_),
    .Z(_129_)
  );
  NAND3_X1 _378_ (
    .A1(_165_),
    .A2(_068_),
    .A3(_155_),
    .ZN(_202_)
  );
  NAND3_X1 _379_ (
    .A1(_067_),
    .A2(_166_),
    .A3(_147_),
    .ZN(_203_)
  );
  AOI22_X1 _380_ (
    .A1(_163_),
    .A2(_175_),
    .B1(_177_),
    .B2(_139_),
    .ZN(_204_)
  );
  NAND3_X1 _381_ (
    .A1(_202_),
    .A2(_203_),
    .A3(_204_),
    .ZN(_205_)
  );
  MUX2_X1 _382_ (
    .A(_076_),
    .B(_205_),
    .S(_173_),
    .Z(_130_)
  );
  AOI22_X1 _383_ (
    .A1(_162_),
    .A2(_175_),
    .B1(_177_),
    .B2(_138_),
    .ZN(_206_)
  );
  AOI221_X1 _384_ (
    .A(_174_),
    .B1(_176_),
    .B2(_146_),
    .C1(_178_),
    .C2(_154_),
    .ZN(_207_)
  );
  NOR2_X1 _385_ (
    .A1(_075_),
    .A2(_173_),
    .ZN(_208_)
  );
  AOI21_X1 _386_ (
    .A(_208_),
    .B1(_207_),
    .B2(_206_),
    .ZN(_131_)
  );
  NAND3_X1 _387_ (
    .A1(_165_),
    .A2(_068_),
    .A3(_153_),
    .ZN(_209_)
  );
  NAND2_X1 _388_ (
    .A1(_145_),
    .A2(_176_),
    .ZN(_210_)
  );
  AOI22_X1 _389_ (
    .A1(_161_),
    .A2(_175_),
    .B1(_177_),
    .B2(_137_),
    .ZN(_211_)
  );
  AND3_X1 _390_ (
    .A1(_173_),
    .A2(_209_),
    .A3(_211_),
    .ZN(_212_)
  );
  NOR2_X1 _391_ (
    .A1(_074_),
    .A2(_173_),
    .ZN(_213_)
  );
  AOI21_X1 _392_ (
    .A(_213_),
    .B1(_212_),
    .B2(_210_),
    .ZN(_132_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _393_ (
    .CK(PCLK),
    .D(_279_),
    .Q(PREADY),
    .QN(_237_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _394_ (
    .CK(PCLK),
    .D(_270_),
    .Q(\mem[1] [0]),
    .QN(_258_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _395_ (
    .CK(PCLK),
    .D(_269_),
    .Q(\mem[1] [1]),
    .QN(_247_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _396_ (
    .CK(PCLK),
    .D(_268_),
    .Q(\mem[1] [2]),
    .QN(_248_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _397_ (
    .CK(PCLK),
    .D(_267_),
    .Q(\mem[1] [3]),
    .QN(_249_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _398_ (
    .CK(PCLK),
    .D(_266_),
    .Q(\mem[1] [4]),
    .QN(_250_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _399_ (
    .CK(PCLK),
    .D(_265_),
    .Q(\mem[1] [5]),
    .QN(_251_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _400_ (
    .CK(PCLK),
    .D(_264_),
    .Q(\mem[1] [6]),
    .QN(_252_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _401_ (
    .CK(PCLK),
    .D(_280_),
    .Q(\mem[1] [7]),
    .QN(_236_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _402_ (
    .CK(PCLK),
    .D(_263_),
    .Q(PRDATA[0]),
    .QN(_257_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _403_ (
    .CK(PCLK),
    .D(_262_),
    .Q(PRDATA[1]),
    .QN(_254_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _404_ (
    .CK(PCLK),
    .D(_261_),
    .Q(PRDATA[2]),
    .QN(_255_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _405_ (
    .CK(PCLK),
    .D(_260_),
    .Q(PRDATA[3]),
    .QN(_256_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _406_ (
    .CK(PCLK),
    .D(_300_),
    .Q(PRDATA[4]),
    .QN(_216_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _407_ (
    .CK(PCLK),
    .D(_299_),
    .Q(PRDATA[5]),
    .QN(_217_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _408_ (
    .CK(PCLK),
    .D(_298_),
    .Q(PRDATA[6]),
    .QN(_218_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFFR_X1 _409_ (
    .CK(PCLK),
    .D(_282_),
    .Q(PRDATA[7]),
    .QN(_234_),
    .RN(PRESETn)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _410_ (
    .CK(PCLK),
    .D(_294_),
    .Q(\mem[2] [0]),
    .QN(_222_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _411_ (
    .CK(PCLK),
    .D(_293_),
    .Q(\mem[2] [1]),
    .QN(_223_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _412_ (
    .CK(PCLK),
    .D(_292_),
    .Q(\mem[2] [2]),
    .QN(_224_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _413_ (
    .CK(PCLK),
    .D(_291_),
    .Q(\mem[2] [3]),
    .QN(_225_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _414_ (
    .CK(PCLK),
    .D(_290_),
    .Q(\mem[2] [4]),
    .QN(_226_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _415_ (
    .CK(PCLK),
    .D(_288_),
    .Q(\mem[2] [5]),
    .QN(_228_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _416_ (
    .CK(PCLK),
    .D(_287_),
    .Q(\mem[2] [6]),
    .QN(_229_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _417_ (
    .CK(PCLK),
    .D(_283_),
    .Q(\mem[2] [7]),
    .QN(_233_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _418_ (
    .CK(PCLK),
    .D(_278_),
    .Q(\mem[3] [0]),
    .QN(_238_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _419_ (
    .CK(PCLK),
    .D(_277_),
    .Q(\mem[3] [1]),
    .QN(_239_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _420_ (
    .CK(PCLK),
    .D(_276_),
    .Q(\mem[3] [2]),
    .QN(_259_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _421_ (
    .CK(PCLK),
    .D(_275_),
    .Q(\mem[3] [3]),
    .QN(_241_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _422_ (
    .CK(PCLK),
    .D(_274_),
    .Q(\mem[3] [4]),
    .QN(_242_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _423_ (
    .CK(PCLK),
    .D(_273_),
    .Q(\mem[3] [5]),
    .QN(_243_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _424_ (
    .CK(PCLK),
    .D(_272_),
    .Q(\mem[3] [6]),
    .QN(_244_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _425_ (
    .CK(PCLK),
    .D(_286_),
    .Q(\mem[3] [7]),
    .QN(_230_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _426_ (
    .CK(PCLK),
    .D(_297_),
    .Q(\mem[0] [0]),
    .QN(_219_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _427_ (
    .CK(PCLK),
    .D(_296_),
    .Q(\mem[0] [1]),
    .QN(_220_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _428_ (
    .CK(PCLK),
    .D(_295_),
    .Q(\mem[0] [2]),
    .QN(_221_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _429_ (
    .CK(PCLK),
    .D(_285_),
    .Q(\mem[0] [3]),
    .QN(_231_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _430_ (
    .CK(PCLK),
    .D(_284_),
    .Q(\mem[0] [4]),
    .QN(_232_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _431_ (
    .CK(PCLK),
    .D(_281_),
    .Q(\mem[0] [5]),
    .QN(_235_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _432_ (
    .CK(PCLK),
    .D(_271_),
    .Q(\mem[0] [6]),
    .QN(_245_)
  );
  (* src = "design.sv:17.3-59.6" *)
  DFF_X1 _433_ (
    .CK(PCLK),
    .D(_289_),
    .Q(\mem[0] [7]),
    .QN(_227_)
  );
  DFFS_X1 _434_ (
    .CK(PCLK),
    .D(_001_),
    .Q(state[0]),
    .QN(_253_),
    .SN(PRESETn)
  );
  DFFR_X1 _435_ (
    .CK(PCLK),
    .D(state[2]),
    .Q(state[1]),
    .QN(_246_),
    .RN(PRESETn)
  );
  DFFR_X1 _436_ (
    .CK(PCLK),
    .D(_002_),
    .Q(state[2]),
    .QN(_240_),
    .RN(PRESETn)
  );
  assign _067_ = PADDR[0];
  assign _068_ = PADDR[1];
  assign _138_ = \mem[0] [5];
  assign _146_ = \mem[1] [5];
  assign _154_ = \mem[2] [5];
  assign _162_ = \mem[3] [5];
  assign _137_ = \mem[0] [4];
  assign _145_ = \mem[1] [4];
  assign _153_ = \mem[2] [4];
  assign _161_ = \mem[3] [4];
  assign _136_ = \mem[0] [3];
  assign _144_ = \mem[1] [3];
  assign _160_ = \mem[3] [3];
  assign _152_ = \mem[2] [3];
  assign _135_ = \mem[0] [2];
  assign _143_ = \mem[1] [2];
  assign _151_ = \mem[2] [2];
  assign _159_ = \mem[3] [2];
  assign _134_ = \mem[0] [1];
  assign _142_ = \mem[1] [1];
  assign _150_ = \mem[2] [1];
  assign _158_ = \mem[3] [1];
  assign _133_ = \mem[0] [0];
  assign _141_ = \mem[1] [0];
  assign _149_ = \mem[2] [0];
  assign _157_ = \mem[3] [0];
  assign _139_ = \mem[0] [6];
  assign _147_ = \mem[1] [6];
  assign _163_ = \mem[3] [6];
  assign _155_ = \mem[2] [6];
  assign _069_ = PENABLE;
  assign _215_ = state[1];
  assign _089_ = PWRITE;
  assign _079_ = PRESETn;
  assign _214_ = state[0];
  assign _080_ = PSEL;
  assign _001_ = _090_;
  assign _002_ = _091_;
  assign _140_ = \mem[0] [7];
  assign _148_ = \mem[1] [7];
  assign _164_ = \mem[3] [7];
  assign _156_ = \mem[2] [7];
  assign _073_ = PRDATA[3];
  assign _260_ = _092_;
  assign _072_ = PRDATA[2];
  assign _261_ = _093_;
  assign _071_ = PRDATA[1];
  assign _262_ = _094_;
  assign _070_ = PRDATA[0];
  assign _263_ = _095_;
  assign _087_ = PWDATA[6];
  assign _264_ = _096_;
  assign _086_ = PWDATA[5];
  assign _265_ = _097_;
  assign _085_ = PWDATA[4];
  assign _266_ = _098_;
  assign _084_ = PWDATA[3];
  assign _267_ = _099_;
  assign _083_ = PWDATA[2];
  assign _268_ = _100_;
  assign _082_ = PWDATA[1];
  assign _269_ = _101_;
  assign _081_ = PWDATA[0];
  assign _270_ = _102_;
  assign _271_ = _103_;
  assign _272_ = _104_;
  assign _273_ = _105_;
  assign _274_ = _106_;
  assign _275_ = _107_;
  assign _276_ = _108_;
  assign _277_ = _109_;
  assign _278_ = _110_;
  assign _078_ = PREADY;
  assign _279_ = _111_;
  assign _088_ = PWDATA[7];
  assign _280_ = _112_;
  assign _281_ = _113_;
  assign _077_ = PRDATA[7];
  assign _282_ = _114_;
  assign _283_ = _115_;
  assign _284_ = _116_;
  assign _285_ = _117_;
  assign _286_ = _118_;
  assign _287_ = _119_;
  assign _288_ = _120_;
  assign _289_ = _121_;
  assign _290_ = _122_;
  assign _291_ = _123_;
  assign _292_ = _124_;
  assign _293_ = _125_;
  assign _294_ = _126_;
  assign _295_ = _127_;
  assign _296_ = _128_;
  assign _297_ = _129_;
  assign _076_ = PRDATA[6];
  assign _298_ = _130_;
  assign _075_ = PRDATA[5];
  assign _299_ = _131_;
  assign _074_ = PRDATA[4];
  assign _300_ = _132_;
endmodule
