`timescale 1ns/1ps
/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

(* top =  1  *)
(* src = "design.sv:2.1-85.10" *)
module apb_slave(PCLK, PRESETn, PSEL, PENABLE, PADDR, PWRITE, PWDATA, PREADY, PRDATA);
  (* src = "design.sv:3.9-3.13" *)
  input PCLK;
  wire PCLK;
  (* src = "design.sv:4.9-4.16" *)
  input PRESETn;
  wire PRESETn;
  (* src = "design.sv:5.9-5.13" *)
  input PSEL;
  wire PSEL;
  (* src = "design.sv:6.9-6.16" *)
  input PENABLE;
  wire PENABLE;
  (* src = "design.sv:7.15-7.20" *)
  input [1:0] PADDR;
  wire [1:0] PADDR;
  (* src = "design.sv:8.9-8.15" *)
  input PWRITE;
  wire PWRITE;
  (* src = "design.sv:9.15-9.21" *)
  input [7:0] PWDATA;
  wire [7:0] PWDATA;
  (* src = "design.sv:10.14-10.20" *)
  output PREADY;
  reg PREADY;
  (* src = "design.sv:11.20-11.26" *)
  output [7:0] PRDATA;
  reg [7:0] PRDATA;
  (* src = "design.sv:17.3-59.6" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  (* src = "design.sv:15.13-15.16" *)
  reg [7:0] \mem[0] ;
  (* src = "design.sv:15.13-15.16" *)
  reg [7:0] \mem[1] ;
  (* src = "design.sv:15.13-15.16" *)
  reg [7:0] \mem[2] ;
  (* src = "design.sv:15.13-15.16" *)
  reg [7:0] \mem[3] ;
  (* onehot = 32'd1 *)
  reg [2:0] state;
  assign _028_ = PADDR[0] & ~(PADDR[1]);
  assign _029_ = ~(PADDR[0] | PADDR[1]);
  assign _030_ = ~(\mem[0] [5] & _029_);
  assign _031_ = ~(\mem[1] [5] & _028_);
  assign _032_ = PADDR[1] & ~(PADDR[0]);
  assign _033_ = ~(\mem[2] [5] & _032_);
  assign _034_ = _031_ & _033_;
  assign _035_ = PADDR[0] & PADDR[1];
  assign _036_ = ~(\mem[3] [5] & _035_);
  assign _037_ = _030_ & _036_;
  assign _000_[5] = ~(_034_ & _037_);
  assign _038_ = ~(\mem[0] [4] & _029_);
  assign _039_ = ~(\mem[1] [4] & _028_);
  assign _040_ = ~(\mem[2] [4] & _032_);
  assign _041_ = _039_ & _040_;
  assign _042_ = ~(\mem[3] [4] & _035_);
  assign _043_ = _038_ & _042_;
  assign _000_[4] = ~(_041_ & _043_);
  assign _044_ = ~(\mem[0] [3] & _029_);
  assign _045_ = ~(\mem[1] [3] & _028_);
  assign _046_ = ~(\mem[2] [3] & _032_);
  assign _047_ = _045_ & _046_;
  assign _048_ = ~(\mem[3] [3] & _035_);
  assign _049_ = _044_ & _048_;
  assign _000_[3] = ~(_047_ & _049_);
  assign _050_ = ~(\mem[0] [2] & _029_);
  assign _051_ = ~(\mem[1] [2] & _028_);
  assign _052_ = ~(\mem[2] [2] & _032_);
  assign _053_ = _051_ & _052_;
  assign _054_ = ~(\mem[3] [2] & _035_);
  assign _055_ = _050_ & _054_;
  assign _000_[2] = ~(_053_ & _055_);
  assign _056_ = ~(\mem[0] [1] & _029_);
  assign _057_ = ~(\mem[1] [1] & _028_);
  assign _058_ = ~(\mem[2] [1] & _032_);
  assign _059_ = _057_ & _058_;
  assign _060_ = ~(\mem[3] [1] & _035_);
  assign _061_ = _056_ & _060_;
  assign _000_[1] = ~(_059_ & _061_);
  assign _062_ = ~(\mem[0] [0] & _029_);
  assign _063_ = ~(\mem[1] [0] & _028_);
  assign _064_ = ~(\mem[2] [0] & _032_);
  assign _065_ = _063_ & _064_;
  assign _066_ = ~(\mem[3] [0] & _035_);
  assign _008_ = _062_ & _066_;
  assign _000_[0] = ~(_065_ & _008_);
  assign _009_ = ~(\mem[0] [6] & _029_);
  assign _010_ = ~(\mem[1] [6] & _028_);
  assign _011_ = ~(\mem[3] [6] & _035_);
  assign _012_ = _010_ & _011_;
  assign _013_ = ~(\mem[2] [6] & _032_);
  assign _014_ = _009_ & _013_;
  assign _000_[6] = ~(_012_ & _014_);
  assign _015_ = PENABLE | ~(state[1]);
  assign _016_ = state[1] | state[0];
  assign _017_ = ~(PSEL & _015_);
  assign _001_ = _016_ & _017_;
  assign _018_ = state[1] & PENABLE;
  assign _019_ = PWRITE & PRESETn;
  assign _020_ = _018_ & _019_;
  assign _004_ = _035_ & _020_;
  assign _021_ = state[0] | _018_;
  assign _002_ = PSEL & _021_;
  assign _007_ = _018_ & ~(PWRITE);
  assign _003_ = _029_ & _020_;
  assign _005_ = _032_ & _020_;
  assign _006_ = _028_ & _020_;
  assign _022_ = ~(\mem[0] [7] & _029_);
  assign _023_ = ~(\mem[1] [7] & _028_);
  assign _024_ = ~(\mem[2] [7] & _032_);
  assign _025_ = _023_ & _024_;
  assign _026_ = ~(\mem[3] [7] & _035_);
  assign _027_ = _022_ & _026_;
  assign _000_[7] = ~(_025_ & _027_);
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) state[0] <= 1'h1;
    else state[0] <= _001_;
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) state[1] <= 1'h0;
    else state[1] <= state[2];
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) state[2] <= 1'h0;
    else state[2] <= _002_;
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[0] <= 1'h0;
    else if (_007_) PRDATA[0] <= _000_[0];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[1] <= 1'h0;
    else if (_007_) PRDATA[1] <= _000_[1];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[2] <= 1'h0;
    else if (_007_) PRDATA[2] <= _000_[2];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[3] <= 1'h0;
    else if (_007_) PRDATA[3] <= _000_[3];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[4] <= 1'h0;
    else if (_007_) PRDATA[4] <= _000_[4];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[5] <= 1'h0;
    else if (_007_) PRDATA[5] <= _000_[5];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[6] <= 1'h0;
    else if (_007_) PRDATA[6] <= _000_[6];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PRDATA[7] <= 1'h0;
    else if (_007_) PRDATA[7] <= _000_[7];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [0] <= PWDATA[0];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [1] <= PWDATA[1];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [2] <= PWDATA[2];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [3] <= PWDATA[3];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [4] <= PWDATA[4];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [5] <= PWDATA[5];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [6] <= PWDATA[6];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_006_) \mem[1] [7] <= PWDATA[7];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) PREADY <= 1'h0;
    else if (state[1]) PREADY <= PENABLE;
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [0] <= PWDATA[0];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [1] <= PWDATA[1];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [2] <= PWDATA[2];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [3] <= PWDATA[3];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [4] <= PWDATA[4];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [5] <= PWDATA[5];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [6] <= PWDATA[6];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_005_) \mem[2] [7] <= PWDATA[7];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [0] <= PWDATA[0];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [1] <= PWDATA[1];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [2] <= PWDATA[2];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [3] <= PWDATA[3];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [4] <= PWDATA[4];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [5] <= PWDATA[5];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [6] <= PWDATA[6];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_004_) \mem[3] [7] <= PWDATA[7];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [0] <= PWDATA[0];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [1] <= PWDATA[1];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [2] <= PWDATA[2];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [3] <= PWDATA[3];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [4] <= PWDATA[4];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [5] <= PWDATA[5];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [6] <= PWDATA[6];
  (* src = "design.sv:17.3-59.6" *)
  always @(posedge PCLK)
    if (_003_) \mem[0] [7] <= PWDATA[7];
endmodule
